# Generated by Django 2.2.5 on 2020-04-09 19:45

import apps.user.utils.user
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(db_index=True, default="", max_length=256, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="", max_length=256, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=256, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="Phone number"),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "token",
                    models.UUIDField(
                        default=apps.user.utils.user.get_token,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"verbose_name": "User", "verbose_name_plural": "Users",},
        ),
    ]
