# Generated by Django 2.2.5 on 2020-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_socialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_streaming',
            field=models.BooleanField(default=True),
        ),
    ]
