# Generated by Django 2.2.5 on 2020-04-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modified")),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.Project"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modified")),
                ("key", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=256)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="stream.Stream"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
