# Generated by Django 2.2.5 on 2020-04-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0002_auto_20200409_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='stream',
        ),
        migrations.AddField(
            model_name='rule',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
