# Generated by Django 2.2.5 on 2020-04-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created',)},
        ),
    ]
