# Generated by Django 2.2.5 on 2020-04-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationService",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modified")),
                (
                    "service",
                    models.CharField(
                        choices=[("vk", "vk.com"), ("telegram", "telegram.com"), ("email", "email")],
                        max_length=64,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=256, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("verification_token", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
